CREATE TABLE IF NOT EXISTS population_groups (
    group_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_code TEXT NOT NULL UNIQUE,
    group_name TEXT NOT NULL,
    min_single_cell_samples INTEGER NOT NULL,
    min_bulk_samples INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS samples (
    sample_id TEXT PRIMARY KEY,
    sample_code TEXT NOT NULL UNIQUE,
    group_id INTEGER NOT NULL REFERENCES population_groups(group_id),
    subject_id TEXT,
    study_id TEXT,
    title TEXT,
    description TEXT,
    species TEXT,
    tissue TEXT,
    condition TEXT,
    collection_site TEXT,
    metadata JSON NOT NULL DEFAULT '{}'::json,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS sample_data_assets (
    asset_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    sample_id TEXT NOT NULL REFERENCES samples(sample_id) ON DELETE CASCADE,
    modality TEXT NOT NULL CHECK (modality IN ('fastq', 'single_cell_h5ad', 'bulk')),
    file_format TEXT NOT NULL CHECK (file_format IN ('fastq.gz', 'h5ad', 'csv', 'tsv', 'txt')),
    file_path TEXT NOT NULL,
    file_name TEXT NOT NULL,
    size_bytes BIGINT,
    checksum TEXT,
    source_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSON NOT NULL DEFAULT '{}'::json,
    created_at TIMESTAMP NOT NULL,
    UNIQUE (sample_id, modality)
);

CREATE TABLE IF NOT EXISTS single_cell_cells (
    asset_id INTEGER NOT NULL REFERENCES sample_data_assets(asset_id) ON DELETE CASCADE,
    obs_index INTEGER NOT NULL,
    cell_type TEXT,
    cluster TEXT,
    sample_barcode TEXT,
    metadata JSON NOT NULL DEFAULT '{}'::json,
    PRIMARY KEY (asset_id, obs_index)
);

INSERT INTO population_groups (group_id, group_code, group_name, min_single_cell_samples, min_bulk_samples)
VALUES
    (1, 'plateau_high_cold', '高原高寒环境人群', 3, 6),
    (2, 'tropical_heat_tolerant', '热带环境耐热人群', 3, 6),
    (3, 'plain_ams_patient', '平原环境人群高原反应患者', 2, 2),
    (4, 'plain_low_altitude', '平原环境低海拔人群', 10, 10)
ON CONFLICT (group_code) DO UPDATE
SET
    group_name = EXCLUDED.group_name,
    min_single_cell_samples = EXCLUDED.min_single_cell_samples,
    min_bulk_samples = EXCLUDED.min_bulk_samples;

CREATE OR REPLACE VIEW vw_group_modality_counts AS
SELECT
    pg.group_id,
    pg.group_code,
    pg.group_name,
    COUNT(DISTINCT CASE WHEN sda.modality = 'single_cell_h5ad' AND sda.is_active THEN s.sample_id END) AS single_cell_sample_count,
    COUNT(DISTINCT CASE WHEN sda.modality = 'bulk' AND sda.is_active THEN s.sample_id END) AS bulk_sample_count,
    COUNT(DISTINCT CASE WHEN sda.modality = 'fastq' AND sda.is_active THEN s.sample_id END) AS fastq_sample_count
FROM population_groups pg
LEFT JOIN samples s ON s.group_id = pg.group_id
LEFT JOIN sample_data_assets sda ON sda.sample_id = s.sample_id
GROUP BY pg.group_id, pg.group_code, pg.group_name;

CREATE OR REPLACE VIEW vw_group_quota_status AS
SELECT
    pg.group_id,
    pg.group_code,
    pg.group_name,
    counts.single_cell_sample_count,
    counts.bulk_sample_count,
    counts.fastq_sample_count,
    pg.min_single_cell_samples,
    pg.min_bulk_samples,
    counts.single_cell_sample_count >= pg.min_single_cell_samples AS single_cell_ok,
    counts.bulk_sample_count >= pg.min_bulk_samples AS bulk_ok
FROM population_groups pg
LEFT JOIN vw_group_modality_counts counts ON counts.group_id = pg.group_id;
